Repository Syrent/SayanVanish, pull requests merged in 2022-11, with the labels that each got.

#27 Velocity | Change player count on MOTD and ServerListPlus support.
  build.gradle
  gradle.properties
  src/main/java/ir/syrent/velocityvanish/velocity/VelocityVanish.kt
  src/main/java/ir/syrent/velocityvanish/velocity/listener/ProxyPingListener.kt
  src/main/resources/velocity-plugin.json
Labels: feature

#30 Velocity | Fix ServerListPlus per server online count size
  src/main/java/ir/syrent/velocityvanish/velocity/VelocityVanish.kt
Labels: bug

#34 Fixes Language file Spaces
  src/main/resources/languages/fa_IR.yml
Labels: enhancement, ignore-for-release

#38 Version increment
  gradle.properties
  src/main/resources/velocity-plugin.json
Labels: enhancement, ignore-for-release

#39 Spigot | Update `settings.yml` comments
  src/main/resources/settings.yml
Labels: enhancement
